name: Deploy KMP wasmJs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ vars.BASE_URL }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build wasmJs
        run: ./gradlew wasmJsBrowserProductionWebpack -PBASE_URL=$BASE_URL

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./composeApp/build/dist/wasmJs/productionExecutable
